### ISSUE TITLE
ebook not appearing with title/author search

### ISSUE THREAD

**Issue by mwillihooper** [lbcclib/findit#397]
Oftentimes when I search Google Scholar or another big "bucket" of content I'll search for part of title + author's name. [This ebook ](https://ebookcentral.proquest.com/lib/linnbenton-ebooks/detail.action?docID=5194655)didn't come up when I searched for _picture this bang_ and I'm wondering why. It does come up with a narrowed title search, and it's in the catalog.

**Comment by sandbergja** [comment]
Back in November, I took a field out of the index called title_and_statement_of_responsibility_t: https://github.com/lbcclib/findit/commit/8f11b02c25417927bd7e7c804a0c190fadccc196#diff-9057d7c20ced9ae84f4f8810279d49f44fccd8afb0486b2c89830d79ab5374c7

It wasn't a publicly visible field, and I didn't think it was doing any good, but I was wrong!  I bet this field was helping with those title + author searches.  I'll try restoring it and see if that helps.  And I'll add that ebook to my test data so that I don't mess it up again. :-)

**Comment by sandbergja** [comment]
This should be fixed as soon as FindIt gets re-indexed (probably this weekend)

**Comment by sandbergja** [comment]
FYI: the first two results for the search "picture this bang" are now correct.
